version: '2'
services:
  proxy-docker:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /home/bluzeadmin/front-end/nginx/data/.well-known/pki-validation:/usr/share/nginx/html/.well-known/pki-validation/
      - /home/bluzeadmin/front-end/nginx:/var/log/nginx/
      - /home/bluzeadmin/front-end/nginx/ssl:/ssl/
